feat: tooltip
arnsbogroup/react-voicearchive pull request #21
Opened 2022-08-31 06:54 UTC by gvhuyssteen

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1265536/187612908-6e4425ca-0b46-412a-8033-5f58fe5859da.png">

2022-08-31 07:09 UTC, RynoVanHuyssteen77 approved these changes

2022-08-31 13:12 UTC, mathiasjakobsen requested changes
How is this a tooltip?

2022-08-31 14:25 UTC, gvhuyssteen commented
<img width="1003" alt="Screenshot 2022-08-31 at 16 23 26" src="https://user-images.githubusercontent.com/1265536/187702706-941540a3-51d4-47e7-b9c5-fe627ea7d23f.png">

2022-09-01 06:17 UTC, mathiasjakobsen requested changes
After testing this, I have a few concerns:

1. If the length of the tooltip boundaries extend the viewport of parent component - how will/should this behave? Always showing on top? Maybe, if we introduce a generic tooltip, we could use https://headlessui.com/ (from Tailwind Labs) to make it a generic popover that can handle different scenarios

2. To giver our UX a bit "smoothness" I wonder if we could add a few ms of transitioning, like on the `<Button />` when showing hidding?

2022-09-01 08:53 UTC, mathiasjakobsen approved these changes

2022-09-02 07:17 UTC, merged