feat: Modal
arnsbogroup/react-voicearchive pull request #27
Opened 2022-09-01 13:54 UTC by gvhuyssteen

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1265536/187931508-22c18676-401d-474d-8349-48adf3ae164f.png">

2022-09-01 14:14 UTC, RynoVanHuyssteen77 approved these changes

2022-09-01 14:25 UTC, mathiasjakobsen requested changes
Could we implement a `onClose` prop? If set this will render an X icon in top right corner, and if clicked fire the callback 🧨 

In addition, implement an `onOutsideClick` similar to the one in AMEs `Aside`. This makes it super convinient to use.

2022-09-02 07:15 UTC, gvhuyssteen commented
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1265536/188080209-f5ef68fd-7922-45e6-907b-006efe88d37f.png">

2022-09-02 08:18 UTC, mathiasjakobsen approved these changes
Looks gooooood 🔥

2022-09-02 08:53 UTC, merged