Added tailwind to avatar
arnsbogroup/react-voicearchive pull request #6
Opened 2022-06-02 10:20 UTC by gvhuyssteen

2022-06-02 15:38 UTC, mathiasjakobsen requested changes
A generel note; I like to use the simple `classnames` lib to work with dynamic classNames ⭐  It look a bit sexier in the codebase, and can catch potential whoopsies ¯\_(ツ)_/¯

2022-06-03 06:15 UTC, gvhuyssteen commented on .npmrc
> +//npm.fontawesome.com/:_authToken=564E391E-17B7-42F1-85FF-4A54192DFFCB
Urgh!   I forgot.

2022-06-03 06:47 UTC, mathiasjakobsen approved these changes

2022-06-07 11:32 UTC, mathiasjakobsen approved these changes

2022-06-13 07:52 UTC, merged